config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "home#index"
	resources :posts do
		resources :comments
		resources :likes
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments,dependent: :destroy
	has_many :likes, dependent: :destroy
	belongs_to :user
	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :posts, dependent: :destroy
  has_many :comments
	has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  protected

	  def after_sign_out_path_for(_resource_or_scope)
	    root_path
	  end

	  
	  # def after_sign_in_path_for(resource)
	    
	  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_post

	def new
		@comment = @post.comments.new
		@post_comments = @post.comments.where.not(id: nil)
	end

	def create
		@comment = @post.comments.new(comment_params)
		if @comment.save
			flash[:success] = 'Your comment was successfully posted!'
      redirect_to request.referer
    else
    	flash[:error] = @comment.errors.full_messages.join(', ')
      redirect_to request.referer
    end
	end

	private
  
	  def find_post
	    @post = Post.find(params[:post_id])
	  end

	  def comment_params
	  	params.require(:comment).permit(:body).merge(user_id: current_user.id)
	  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
	before_action :find_post
	before_action :find_like, only: [:destroy]

	def create
		if already_liked?
    	flash[:notice] = "You can't like more than once"
  	else
    	@post.likes.create(user_id: current_user.id)
  	end
    redirect_to posts_path
  end

  def destroy
	  if !(already_liked?)
	    flash[:notice] = "Cannot unlike"
	  else
	    @like.destroy
	  end
	  redirect_to posts_path
	end
  
  private
  
	  def find_post
	    @post = Post.find(params[:post_id])
	  end

	  def find_like
   		@like = @post.likes.find(params[:id])
		end

	  def already_liked?
		  Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!,except: %i[ index]
	before_action :find_post,except: %i[new index create]

	def index
		@posts = Post.all
	end

	def new
		@post = current_user.posts.new
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			flash[:success] = "Post Created Successfully"
			redirect_to posts_path
		else
			flash[:error] = @post.errors.full_messages.join(', ')
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Post Updated Successfully"
		else
			flash[:error] = @post.errors.full_messages.join(', ')
		end
		redirect_to edit_post_path(@post)
	end

	def destroy
	end

	private
		def post_params
			params.require(:post).permit(:title,:description,:image)
		end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment_form.html.erb
<div class="row mt-3">
	<div class="col-md-12">
		<%= form_for @comment,url: post_comments_path(@post) do |f|%>
			<div class="form-group">
				<%= f.text_field :body,class: "form-control",required: true%>
				<%= f.submit "Comment",class: 'btn btn-success mt-1'%>
			</div>
		<% end %>
	</div>
</div>

app/views/comments/new.html.erb
<div class="header">
	<div class="row">
		<div class="col-md-6">
  		<h2 class="float-left">Post</h2>
  	</div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <h2><%= @post.title %></h2>
      <h5><%= raw @post.description %></h5>
     	<div class="fakeimg thumbnail">
      	<% if @post.image.attached? %>
          <%= image_tag main_app.url_for(@post.image) ,class: "w-100"%>
      	<% end %>
    	</div>
    	<div class="row mt-3">
         <div class="col-md-12 d-flex m-auto">
          <h5 class="text-dark"><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></h5>
          <% already_like_post = @post.likes.find { |like| like.user_id == current_user.id} %>
          <% if already_like_post %>
            <%= button_to post_like_path(@post,already_like_post), method: :delete,class: "btn btn-info ml-3" do %>
              <span class="glyphicon glyphicon-thumbs-down"></span> Unlike
            <% end %>
          <% else %>
            <%= button_to post_likes_path(@post), method: :post,class: "btn btn-info ml-3" do %>
              <span class="glyphicon glyphicon-thumbs-up"></span> Like
            <% end %>
          <% end %>
          <h5 class="text-dark ml-3"><%= @post_comments.count %>  <%= (@post_comments.count) == 1 ? 'Comment' : 'Comments' %> </h5>
    	   </div>
      </div>
    </div>
  </div>
</div>
<% if @post_comments.any?%>
	<div class="row mt-2">
		<div class="col-md-12">
			<% @post_comments.each do |comment|%>
				<h3 class="text-dark"><%= comment.user.email%></h3>
				<h4 class="text-danger"><%= comment.body %></h4>
			<% end%>
		</div>
	</div>
<% end %>

<%= render :partial => 'comment_form'%>

app/views/home/index.html.erb
<%#= render '/layouts/header' %>
<div id="content">
	<div class="row">
		<div class="col-md-12">
			<%= image_tag 'blogging-stats-featured.png',class: 'w-100'%>
		</div>
	</div>
</div>
<%#= render '/layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div id="footer-inner">
		<p>&copy; Copyright</p>
		<div class="clr"></div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
		<div id="header-inner">	
			<div id="logo">
				<h1><a href="/">Blogger<span>App</span></a></h1>
			</div>
			<div id="top-nav">
				<ul>
			  <% if current_user.present? %>
        	<li><%= link_to 'Social',posts_path %></li>
        	<li><%= link_to "Logout",destroy_user_session_path, method: :delete,data: { confirm: "Are you sure?" } %> </li>
        <% else %>
					<li><%= link_to "Login", "#loginModal", "data-toggle" => "modal" %></li>
					<li><%= link_to "Signup", "#registerModal", "data-toggle" => "modal"%></li>
				<% end %>
				</ul>
			</div>
			<div class="clr"></div>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
	<div id="page">
  	<div class="container-fluid">
  		<div class="row">
				<div class="col-md-12">
         <%= render '/layouts/header' %>
					<%= bootstrap_flash %>
    			<%= yield %>
          <%= render '/layouts/footer' %>
    		</div>
    	</div>
    </div>
  </div>
  <%= render :partial => 'shared/login'%>
  <%= render :partial => 'shared/register'%>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-group">
	 <%= f.label :title%>
   <%= f.text_field :title,class: "form-control",placeholder: "Title *",required: true%>
</div>
<div class="form-group">
	 <%= f.label :description%>
   <%= f.cktext_area :description,class: "form-control",placeholder: "Description",required: true%>
</div>
 <div class="form-group">
 	 <%= f.label :image%>
   <%= f.file_field :image,class: "form-control image"%>
   <div id="image" class="thumbnail mt-3 position-relative">
   </div>
</div>

app/views/posts/index.html.erb
<div class="header">
	<div class="row">
		<div class="col-md-6">
  		<h2 class="float-left">Posts</h2>
  	</div>
	  <div class="col-md-6">
	  	 <%= link_to "Add Blog", new_post_path,class: 'btn btn-success' %>
	  </div>
  </div>
</div>

<% if @posts.any? %>
<% @posts.each_with_index do |post,index|%>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <h2><%= post.title %></h2>
      <h5><%= raw post.description %></h5>
     	<div class="fakeimg thumbnail">
      	<% if post.image.attached? %>
          <%= image_tag main_app.url_for(post.image) ,class: "w-100"%>
      	<% end %>
    	</div>
    	<div class="row mt-3">
         <div class="col-md-12 d-flex m-auto">
           <h5><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></h5>
          <% already_like_post = post.likes.find { |like| like.user_id == current_user.id} %>
          <% if already_like_post %>
            <%= button_to post_like_path(post,already_like_post), method: :delete,class: "btn btn-info ml-3" do %>
              <span class="glyphicon glyphicon-thumbs-down"></span> Unlike
            <% end %>
          <% else %>
            <%= button_to post_likes_path(post), method: :post,class: "btn btn-info ml-3" do %>
              <span class="glyphicon glyphicon-thumbs-up"></span> Like
            <% end %>
          <% end %>
          <%= link_to new_post_comment_path(post),class: "btn btn-success ml-3" do %> 
            <span class="glyphicon glyphicon-comment"></span> Comment
          <% end %>
    	   </div>
      </div>
      <% if post.comments.any? %>
        <div class="row mt-2">
          <div class="col-md-12">
            <% post.comments.each do |comment|%>
              <h3 class="text-dark"><%= comment.user.email%></h3>
              <h4 class="text-danger"><%= comment.body %></h4>
            <% end%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= "No Blog is found." %>,
    <%= link_to "Add Blog", new_post_path %>!
  </div>
<% end %>

<style type="text/css">
	body {
  font-family: Arial;
  padding: 20px;
  background: #f1f1f1;
}

/* Header/Blog Title */
.header {
  padding: 30px;
  font-size: 40px;
  text-align: center;
  background: white;
}

/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {
  float: left;
  width: 75%;
}


/* Fake image */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Add a card effect for articles */
.card {
  background-color: white;
  padding: 20px;
  margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
  .leftcolumn, .rightcolumn {
    width: 100%;
    padding: 0;
  }
}
</style>

app/views/posts/new.html.erb
<div class="container p-5">
	<div class="row">
		<div class="col-md-12">
		  <%= form_for @post,url: posts_path, method: :post  do |f| %>
		  	<%= render partial: 'form', locals: { f: f } %>
		  	<div class="d-flex justify-content-center">
			  	<%= f.submit 'Submit', {class: 'btn btn-success', data: { disable_with: "Saving..." }} %>
					<span class="p-2">OR</span>	
					<%= link_to 'Cancel', posts_path, class: 'btn btn-danger' %>
				</div>
		  <% end%>
		</div>
	</div>
</div> 

app/views/shared/_login.html.erb
<div class="modal fade common-modal" id="loginModal">
 <div class="modal-dialog max-WT-500">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
       <div class="modal-body">
          <%= form_with scope: :user,url: user_session_path,:html => { class: "main-form p-0",id: "login_page"},local: true  do |f| %>
          <div class="form-group">
             <%= f.email_field :email,class: "form-control",placeholder: "Email ID"%>
          </div>
          <div class="form-group password-field">
            <%= f.password_field :password,class: "form-control",placeholder: "Password"%>
          </div>
          <div class="form-group clearfix mt25">
             <a href="javascript:;" data-target="#forgotModal" class="forget-text f-right" data-toggle="modal" data-dismiss="modal">Forget-Password ?</a>
             <div class="checkbox-design-block">
                <label class="checkbox-design">
                <input type="checkbox" name="remember_me">
                <span></span>Remember me
                </label>
             </div>
          </div>
          <div class="button-block mb20">
             <button type="submit" class="btn btn-success w-100">LOGIN</button>
          </div>
          <div class="reg-text text-center">
             <p>DON’T HAVE AN ACCOUNT? <a href="javascript:;" data-target="#registerModal" data-toggle="modal" data-dismiss="modal">SIGN UP</a></p>
          </div>
          <% end %>
       </div>
    </div>
 </div>
</div>

app/views/shared/_register.html.erb
<div class="modal fade common-modal" id="registerModal">
   <div class="modal-dialog max-WT-500">
      <div class="modal-content py-0">
      	<div class="modal-header text-center">
          <h4 class="modal-title w-100 font-weight-bold">Sign up</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
         <div class="modal-body">
            <%= form_with scope: :user,url: user_registration_path,:html => { class: "main-form p-0",id: "register_page"},local: true  do  |f| %>
            <div class="form-group">
            	<%= f.email_field :email, class: 'form-control',placeholder: "Email ID*",autocomplete: false  %>
            </div>
            <div class="form-group">
            	<%= f.password_field :password, class: 'form-control',placeholder: "Password *",autocomplete: false%>
            </div>
            <div class="form-group">
            	<%= f.password_field :password_confirmation, class: 'form-control',placeholder: "Confirm Password *",autocomplete: false%>
            </div>
            <div class="button-block my-3">
               <button type= "submit" class="btn btn-success w-100">REGISTER</button>
            </div>
            <div class="reg-text text-center">
               <p>Already have an account? <a href="javascript:;" data-target="#loginModal" data-toggle="modal" data-dismiss="modal">LOGIN</a></p>
            </div>
            <% end %>
         </div>
      </div>
   </div>
</div>